# Generated by Django 3.2 on 2021-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='total',
            field=models.IntegerField(blank=True),
        ),
    ]
