# Generated by Django 3.2 on 2021-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pokemon_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
