# Generated by Django 3.2 on 2021-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pokemon_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='generation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sp_atk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='sp_def',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(null=True),
        ),
    ]
