# Generated by Django 3.2 on 2021-04-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210422_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='legendary',
            field=models.BooleanField(null=True),
        ),
    ]
