# Generated by Django 3.2 on 2021-04-22 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pokemon_legendary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
